#!/usr/bin/env bash

# ============================================================
# Ouriva — Provision an Individual Early-Tester Instance
# ============================================================
# Spins up a single-tenant instance for one real early adopter,
# separate from the public demo and from any other tester's
# instance. This is the "do things that don't scale" step: one
# command per person, by hand, until there are enough testers
# that a real multi-tenant Cloud product is worth building.
#
# What it creates:
#   ~/ouriva-instances/<name>/docker-compose.yml   (unique port, password)
#   A running app + db pair, isolated from every other instance
#   (own Compose project name, own network, own volume)
#
# By default the instance starts empty (real user data only) —
# pass --seed to pre-load the same realistic sample data the
# demo uses, e.g. before a screen-share call with that person.
#
# Usage (run from the ouriva-app repo root, on the host that
# will actually run the instance — e.g. the Oracle VM):
#   ./deploy/provision-instance.sh alice
#   ./deploy/provision-instance.sh alice --seed
#
# After it prints the port, add a block to your Caddyfile:
#   alice.ouriva.app {
#       reverse_proxy localhost:<PORT>
#   }
# (the script does this automatically if /etc/caddy/Caddyfile
# exists — see Step 5 below)
# ============================================================

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <instance-name> [--seed]"
  echo "  <instance-name>: lowercase letters, numbers, hyphens only (used as a subdomain)"
  exit 1
fi

NAME="$1"
SEED=false
if [ "${2:-}" = "--seed" ]; then
  SEED=true
fi

if ! [[ "${NAME}" =~ ^[a-z0-9-]+$ ]]; then
  echo "Error: instance name must be lowercase letters, numbers, and hyphens only (got: ${NAME})"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
INSTANCES_DIR="${HOME}/ouriva-instances"
INSTANCE_DIR="${INSTANCES_DIR}/${NAME}"
PROJECT_NAME="ouriva-${NAME}"
APP_IMAGE="ouriva:latest"
MIGRATOR_IMAGE="ouriva:migrator"
BASE_PORT=3200
CADDYFILE="/etc/caddy/Caddyfile"

if [ -d "${INSTANCE_DIR}" ]; then
  echo "Error: ${INSTANCE_DIR} already exists — an instance named '${NAME}' may already be running."
  echo "To remove it first: docker compose -p ${PROJECT_NAME} -f ${INSTANCE_DIR}/docker-compose.yml down -v"
  exit 1
fi

echo "=== Provisioning Ouriva instance: ${NAME} ==="

# ----------------------------------------------------------
# Step 1: Find a free host port, starting from BASE_PORT.
# Keeps every instance (and the demo, which uses 3100) on its
# own port so they can all run side by side on one host.
# ----------------------------------------------------------
echo "[1/5] Finding a free port..."
PORT="${BASE_PORT}"
while docker ps --format '{{.Ports}}' | grep -q ":${PORT}->"; do
  PORT=$((PORT + 1))
done
echo "      Using port ${PORT}."

# ----------------------------------------------------------
# Step 2: Generate a unique DB password and write the
# instance's docker-compose.yml from a template.
# ----------------------------------------------------------
echo "[2/5] Writing ${INSTANCE_DIR}/docker-compose.yml..."
mkdir -p "${INSTANCE_DIR}"
DB_PASSWORD="$(openssl rand -hex 16)"

cat > "${INSTANCE_DIR}/docker-compose.yml" <<COMPOSE_EOF
# Generated by provision-instance.sh for tester: ${NAME}
# Do not edit by hand — re-run the script if you need to change it.
name: ${PROJECT_NAME}

services:
  app:
    image: ${APP_IMAGE}
    ports:
      - "${PORT}:3000"
    environment:
      - DATABASE_URL=postgresql://ouriva:${DB_PASSWORD}@db:5432/ouriva
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ouriva
      POSTGRES_USER: ouriva
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ouriva -d ouriva"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
COMPOSE_EOF

# ----------------------------------------------------------
# Step 3: Ensure the app and migrator images exist (build
# only if missing — this does not rebuild on every provision,
# so it won't clobber a version another instance is using).
# ----------------------------------------------------------
echo "[3/5] Ensuring images exist (building only if missing)..."
docker image inspect "${APP_IMAGE}" >/dev/null 2>&1 || docker build -t "${APP_IMAGE}" "${PROJECT_DIR}"
docker image inspect "${MIGRATOR_IMAGE}" >/dev/null 2>&1 || docker build --target builder -t "${MIGRATOR_IMAGE}" "${PROJECT_DIR}"

# ----------------------------------------------------------
# Step 4: Start the instance, migrate, and optionally seed.
# ----------------------------------------------------------
echo "[4/5] Starting instance..."
docker compose -p "${PROJECT_NAME}" -f "${INSTANCE_DIR}/docker-compose.yml" up -d

echo "      Waiting for the database to be healthy..."
until docker compose -p "${PROJECT_NAME}" -f "${INSTANCE_DIR}/docker-compose.yml" exec -T db pg_isready -U ouriva -d ouriva >/dev/null 2>&1; do
  sleep 1
done

SEED_CMD="npx prisma migrate deploy"
if [ "${SEED}" = true ]; then
  SEED_CMD="npx prisma migrate deploy && npx prisma db seed"
fi

docker run --rm \
  --network "${PROJECT_NAME}_default" \
  -e "DATABASE_URL=postgresql://ouriva:${DB_PASSWORD}@db:5432/ouriva" \
  "${MIGRATOR_IMAGE}" \
  sh -c "${SEED_CMD}"

# ----------------------------------------------------------
# Step 5: Wire up the reverse proxy, if Caddy is installed.
# Appends a routing block rather than overwriting the file,
# so existing sites (the demo, other testers) are untouched.
# ----------------------------------------------------------
echo "[5/5] Configuring reverse proxy..."
if [ -f "${CADDYFILE}" ]; then
  {
    echo ""
    echo "${NAME}.ouriva.app {"
    echo "    reverse_proxy localhost:${PORT}"
    echo "}"
  } | sudo tee -a "${CADDYFILE}" >/dev/null
  sudo systemctl reload caddy
  echo "      Added ${NAME}.ouriva.app to ${CADDYFILE} and reloaded Caddy."
else
  echo "      ${CADDYFILE} not found — add this block manually once Caddy is installed:"
  echo ""
  echo "      ${NAME}.ouriva.app {"
  echo "          reverse_proxy localhost:${PORT}"
  echo "      }"
fi

echo ""
echo "=== Instance '${NAME}' is up ==="
echo "  Local:  http://localhost:${PORT}"
echo "  Public: https://${NAME}.ouriva.app  (once DNS + Caddy are wired up)"
echo "  Seeded with sample data: ${SEED}"
